### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by TAndras** [Teaching-projects/-SZE-MOSZE-2020-BDFANS--Closed#21]
A projektunk végső leadásával kapcsolatban lenne még néhány megjegyzésünk:

A renderer-be az időkorlátok miatt csak részmegoldás került be. A Textstream settelése nem az elvárások szerint működik.

A deployeolt dokumentációnkban valamiért amikor a header fájlokat próbáljuk elérni 404-es hibát kapunk, viszont ha lokálisan próbálom futtatni, vagy feltöltöm valahova máshova, akkor azokat rendesen el lehet érni.

Végül a unittesztelt funkciók számítása során, nem tudtuk hogy a Unit osztály esetén hogyan kell kezelni az olyan funkciókat amiket egy gyermekben teszteltünk és nincsenek felülírva, ezért ezeket az őshöz számítottuk

**Comment by TAndras** [comment]
@hegyhati Elnézést a zavarásért, de szeretnénk érdeklődni, hogy mi a helyzet a mi csapatunkkal, mert mi még nem kaptunk visszajelzést a projektünkre.

**Comment by hegyhati** [comment]
Valamiert nem kaptam notifet, vagy eltunt. Fura. Meg fogom nezni.

**Comment by hegyhati** [comment]
No, marketingesnek ne menjetek, de amugy rendben van. Szabolcsnak nyilvan erre nem tudok mit adni, tobbieknek jar a jeles.
